package com.powercut.editor.domain.filter

/**
 * Single source of truth for the Filters category.
 *
 * Every filter shown in the Filters panel carries:
 *  - [FilterDef] metadata (id, display name, category) used by the UI list, and
 *  - a REAL FFmpeg `-vf` filter string via [ffmpeg].
 *
 * The live preview parses the SAME string (via [ffmpeg]) into a Compose
 * [androidx.compose.ui.graphics.ColorMatrix], and the export pipeline
 * ([com.powercut.editor.domain.processing.VideoProcessor.colorGradeChain])
 * delegates to [ffmpeg] as well. Preview and export therefore read from the
 * exact same definition and can never diverge.
 */
object FilterCatalog {

    data class FilterDef(
        val id: String,
        val name: String,
        val category: String
    )

    /** Filters shown in the Filters panel, in display order. */
    val all: List<FilterDef> = listOf(
        FilterDef("none", "Original", "basic"),
        FilterDef("grayscale", "B&W", "basic"),
        FilterDef("sepia", "Sepia", "basic"),
        FilterDef("invert", "Invert", "basic"),
        FilterDef("warm", "Warm", "basic"),
        FilterDef("cool", "Cool", "basic"),
        FilterDef("vintage", "Vintage", "vintage"),
        FilterDef("dramatic", "Drama", "basic"),
        FilterDef("negative", "Negative", "basic"),
        FilterDef("noir", "Noir", "cinema"),
        FilterDef("cinematic", "Cinematic", "cinema"),
        FilterDef("teal", "Teal", "cinema"),
        FilterDef("orange", "Orange", "cinema"),
        FilterDef("lomo", "Lomo", "vintage"),
        FilterDef("polaroid", "Polaroid", "vintage"),
        FilterDef("holga", "Holga", "vintage"),
        FilterDef("diana", "Diana", "vintage"),
        FilterDef("film", "Film", "film"),
        FilterDef("super8", "Super8", "film"),
        FilterDef("vhs_tape", "VHS", "vintage"),
        FilterDef("kodak", "Kodak", "film"),
        FilterDef("fuji", "Fuji", "film"),
        FilterDef("agfa", "Agfa", "film"),
        FilterDef("ilford", "Ilford", "film"),
        FilterDef("portra", "Portra", "film"),
        FilterDef("velvia", "Velvia", "film"),
        FilterDef("provia", "Provia", "film"),
        FilterDef("astia", "Astia", "film"),
        FilterDef("monochrome", "Mono", "basic"),
        FilterDef("high_contrast", "Hi Contrast", "basic"),
        FilterDef("low_contrast", "Lo Contrast", "basic"),
        FilterDef("high_saturation", "Hi Saturation", "basic"),
        FilterDef("low_saturation", "Lo Saturation", "basic"),
        FilterDef("bright", "Bright", "basic"),
        FilterDef("dark", "Dark", "basic"),
        FilterDef("soft", "Soft", "mood"),
        FilterDef("sharp", "Sharp", "mood"),
        FilterDef("dreamy", "Dreamy", "mood"),
        FilterDef("glow", "Glow", "mood"),
        FilterDef("haze", "Haze", "mood"),
        FilterDef("matte", "Matte", "mood"),
        FilterDef("litho", "Litho", "vintage"),
        FilterDef("sepia_warm", "Sepia Warm", "vintage"),
        FilterDef("sepia_cool", "Sepia Cool", "vintage"),
        FilterDef("red_boost", "Red+", "mood"),
        FilterDef("blue_boost", "Blue+", "mood"),
        FilterDef("green_boost", "Green+", "mood"),
        FilterDef("purple_haze", "Purple Haze", "neon"),
        FilterDef("pink_dream", "Pink Dream", "neon"),
        FilterDef("amber", "Amber", "mood"),
        FilterDef("emerald", "Emerald", "mood"),
        FilterDef("sapphire", "Sapphire", "mood"),
        FilterDef("ruby", "Ruby", "mood"),
        FilterDef("bronze", "Bronze", "mood"),
        FilterDef("platinum", "Platinum", "mood"),
        FilterDef("neon_city", "Neon City", "neon"),
        FilterDef("retro_wave", "Retro Wave", "neon"),
        FilterDef("synthwave", "Synthwave", "neon"),
        FilterDef("analog", "Analog", "vintage"),
        FilterDef("tokyo", "Tokyo", "cinema"),
        FilterDef("nyc", "NYC", "cinema"),
        FilterDef("paris", "Paris", "cinema"),
        FilterDef("miami", "Miami", "neon"),
        FilterDef("desert", "Desert", "mood"),
        FilterDef("ocean", "Ocean", "mood"),
        FilterDef("autumn", "Autumn", "mood"),
        FilterDef("winter", "Winter", "mood"),
        FilterDef("spring", "Spring", "mood"),
        FilterDef("summer", "Summer", "mood"),
        // ── User-requested 72 filters (new entries) ──
        FilterDef("blur_light", "Blur Light", "adjust"),
        FilterDef("blur_medium", "Blur Med", "adjust"),
        FilterDef("blur_heavy", "Blur Heavy", "adjust"),
        FilterDef("gaussian_blur", "Gaussian", "adjust"),
        FilterDef("sharpen_strong", "Sharp+", "adjust"),
        FilterDef("brightness_10", "Bright +10", "adjust"),
        FilterDef("brightness_20", "Bright +20", "adjust"),
        FilterDef("brightness_30", "Bright +30", "adjust"),
        FilterDef("brightness_neg10", "Dark -10", "adjust"),
        FilterDef("brightness_neg20", "Dark -20", "adjust"),
        FilterDef("contrast_20", "Contrast +20", "adjust"),
        FilterDef("contrast_40", "Contrast +40", "adjust"),
        FilterDef("contrast_neg20", "Contrast -20", "adjust"),
        FilterDef("saturation_0", "Sat 0%", "adjust"),
        FilterDef("saturation_50", "Sat 50%", "adjust"),
        FilterDef("saturation_150", "Sat 150%", "adjust"),
        FilterDef("saturation_200", "Sat 200%", "adjust"),
        FilterDef("vignette", "Vignette", "adjust"),
        FilterDef("vignette_strong", "Vignette+", "adjust"),
        FilterDef("hflip", "H Flip", "transform"),
        FilterDef("vflip", "V Flip", "transform"),
        FilterDef("mirror_lr", "Mirror LR", "transform"),
        FilterDef("mirror_tb", "Mirror TB", "transform"),
        FilterDef("rotate_90", "Rotate 90°", "transform"),
        FilterDef("rotate_180", "Rotate 180°", "transform"),
        FilterDef("rotate_270", "Rotate 270°", "transform"),
        FilterDef("green_tint", "Green Tint", "mood"),
        FilterDef("curves_drama", "Hi Con Drama", "cinema"),
        FilterDef("curves_retro", "Faded Retro", "vintage"),
        FilterDef("curves_highlight", "Highlights", "adjust"),
        FilterDef("increase_red", "Red+", "color"),
        FilterDef("increase_green", "Green+", "color"),
        FilterDef("increase_blue", "Blue+", "color"),
        FilterDef("decrease_red", "Red-", "color"),
        FilterDef("decrease_green", "Green-", "color"),
        FilterDef("decrease_blue", "Blue-", "color"),
        FilterDef("solarize", "Solarize", "effect"),
        FilterDef("solarize_strong", "Solarize+", "effect"),
        FilterDef("posterize_8", "Posterize 8", "effect"),
        FilterDef("posterize_4", "Posterize 4", "effect"),
        FilterDef("edge_detect", "Edge Detect", "effect"),
        FilterDef("emboss_filter", "Emboss", "effect"),
        FilterDef("film_grain", "Film Grain", "effect"),
        FilterDef("film_grain_heavy", "Grain Heavy", "effect"),
        FilterDef("pixelate", "Pixelate", "effect"),
        FilterDef("pixelate_medium", "Pixelate Med", "effect"),
        FilterDef("color_swap", "Color Swap", "effect"),
        FilterDef("sepia_vignette", "Sepia+Vig", "vintage"),
        FilterDef("warm_vintage_combo", "Warm Vintage", "vintage"),
        FilterDef("cold_blue_combo", "Cold Blue", "cinema"),
        FilterDef("vivid_cinema", "Vivid Cinema", "cinema"),
        FilterDef("soft_dreamy", "Soft Dreamy", "mood"),
        FilterDef("grayscale_contrast", "B&W+Con", "basic"),
        FilterDef("blue_monochrome", "Blue Mono", "color"),
        FilterDef("red_monochrome", "Red Mono", "color"),
        FilterDef("green_monochrome", "Green Mono", "color"),
        FilterDef("purple_tone", "Purple", "color"),
        FilterDef("yellow_tone", "Yellow", "color"),
        FilterDef("cyan_tone", "Cyan", "color"),
        FilterDef("magenta_tone", "Magenta", "color"),
        // ── v7.3 — EXTENDED PROFESSIONAL FILTER LIBRARY (added per user request) ──
        // Cinema / mood / neon / adjust — CapCut / KineMaster class
        FilterDef("teal_orange", "Teal & Orange", "cinema"),
        FilterDef("matrix", "Matrix", "neon"),
        FilterDef("blade_runner", "Blade Runner", "neon"),
        FilterDef("tron", "Tron", "neon"),
        FilterDef("vaporwave2", "Vaporwave 2", "neon"),
        FilterDef("outrun", "Outrun", "neon"),
        FilterDef("laser", "Laser Grid", "neon"),
        FilterDef("cyberpunk_neon", "Cyberpunk", "neon"),
        FilterDef("hollywood", "Hollywood", "cinema"),
        FilterDef("oscar", "Oscar", "cinema"),
        FilterDef("thriller", "Thriller", "cinema"),
        FilterDef("horror", "Horror", "mood"),
        FilterDef("romance", "Romance", "mood"),
        FilterDef("action", "Action", "mood"),
        FilterDef("documentary", "Documentary", "cinema"),
        FilterDef("news", "News", "basic"),
        FilterDef("sport", "Sport", "mood"),
        FilterDef("fashion", "Fashion", "mood"),
        FilterDef("wedding_warm", "Wedding", "mood"),
        FilterDef("birthday", "Birthday", "mood"),
        FilterDef("baby", "Baby", "mood"),
        FilterDef("kids", "Kids", "mood"),
        FilterDef("nature_green", "Nature", "mood"),
        FilterDef("forest", "Forest", "mood"),
        FilterDef("mountain", "Mountain", "mood"),
        FilterDef("beach", "Beach", "mood"),
        FilterDef("tropical", "Tropical", "mood"),
        FilterDef("city_day", "City Day", "mood"),
        FilterDef("city_night", "City Night", "mood"),
        FilterDef("studio", "Studio", "basic"),
        FilterDef("moonlight", "Moonlight", "mood"),
        FilterDef("starlight", "Starlight", "mood"),
        FilterDef("rainy_window", "Rainy", "mood"),
        FilterDef("foggy_morning", "Foggy", "mood"),
        FilterDef("snowy_day", "Snowy", "mood"),
        FilterDef("autumn_leaves", "Autumn", "mood"),
        FilterDef("cherry_blossom", "Cherry", "mood"),
        FilterDef("lavender", "Lavender", "mood"),
        FilterDef("rose_gold", "Rose Gold", "mood"),
        FilterDef("teal_grade", "Teal Grade", "cinema"),
        FilterDef("orange_grade", "Orange Grade", "cinema"),
        FilterDef("orange_teal", "Orange+Teal", "cinema"),
        FilterDef("bleach_bypass", "Bleach", "cinema"),
        FilterDef("day_for_night", "Day→Night", "cinema"),
        FilterDef("cross_process", "Cross", "effect"),
        FilterDef("lomo_fisheye", "Lomo Fish", "vintage"),
        FilterDef("instagram_1977", "1977", "vintage"),
        FilterDef("instagram_brannan", "Brannan", "vintage"),
        FilterDef("instagram_earlybird", "Earlybird", "vintage"),
        FilterDef("instagram_hefe", "Hefe", "vintage"),
        FilterDef("instagram_lofi", "LoFi IG", "vintage"),
        FilterDef("instagram_ludwig", "Ludwig", "vintage"),
        FilterDef("instagram_nashville", "Nashville", "vintage"),
        FilterDef("instagram_sutro", "Sutro", "vintage"),
        FilterDef("instagram_toaster", "Toaster", "vintage"),
        FilterDef("instagram_valencia", "Valencia", "vintage"),
        FilterDef("instagram_walden", "Walden", "vintage"),
        FilterDef("instagram_xproii", "X-Pro II", "vintage"),
        FilterDef("bw_classic", "B&W Classic", "basic"),
        FilterDef("bw_fade", "B&W Fade", "basic"),
        FilterDef("bw_strong", "B&W Strong", "basic"),
        FilterDef("sepia_light", "Sepia Light", "vintage"),
        FilterDef("sepia_dark", "Sepia Dark", "vintage"),
        FilterDef("cream", "Cream", "vintage"),
        FilterDef("matte_film", "Matte Film", "vintage"),
        FilterDef("kodak_ektar", "Ektar", "film"),
        FilterDef("kodak_portra", "Portra", "film"),
        FilterDef("fuji_superia", "Superia", "film"),
        FilterDef("fuji_velvia", "Velvia", "film"),
        FilterDef("ilford_hp5", "HP5", "film"),
        FilterDef("ilford_delta", "Delta", "film"),
        FilterDef("cinestill_800", "CineStill 800", "film"),
        FilterDef("bw_silver", "Silver B&W", "basic"),
        FilterDef("bw_ir", "B&W IR", "basic"),
        FilterDef("golden_hour", "Golden Hour", "mood"),
        FilterDef("blue_hour", "Blue Hour", "mood"),
        FilterDef("magic_hour", "Magic Hour", "mood"),
        FilterDef("pastel_sunset", "Pastel Sunset", "mood"),
        FilterDef("dream_pop", "Dream Pop", "mood"),
        FilterDef("lofi_chill", "LoFi Chill", "vintage"),
        FilterDef("studio_neon", "Studio Neon", "neon"),
        FilterDef("k_pop", "K-Pop", "neon"),
        FilterDef("insta_airy", "Airy", "mood"),
        FilterDef("insta_moody", "Moody", "mood"),
        FilterDef("insta_clean", "Clean", "mood"),
        FilterDef("insta_fade_warm", "Fade Warm", "vintage"),
        FilterDef("insta_fade_cool", "Fade Cool", "vintage")
    )

    /** Real FFmpeg `-vf` sub-filter chain for a filter id ("" when none/unknown). */
    fun ffmpeg(id: String): String {
        val f = id.lowercase().replace("-", "_").replace(" ", "_")
        return CHAIN[f] ?: ""
    }

    /** True when the id maps to a real (non-empty) FFmpeg chain. */
    fun isReal(id: String): Boolean = ffmpeg(id).isNotBlank()

    private val CHAIN: Map<String, String> = mapOf(
        "none" to "",
        "sepia" to "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131",
        "grayscale" to "hue=s=0",
        "mono" to "hue=s=0",
        "black_white" to "hue=s=0",
        "monochrome" to "hue=s=0",
        "invert" to "negate",
        "negative" to "negate",
        "warm" to "eq=saturation=1.1,colorbalance=rs=0.08:gs=0.02:rm=0.05",
        "cool" to "eq=saturation=1.05,colorbalance=bs=0.1:gm=-0.03:bm=0.05",
        "vintage" to "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,eq=saturation=0.8:contrast=1.1:gamma=1.1,vignette=angle=PI/4",
        "dramatic" to "eq=contrast=1.4:saturation=1.3:gamma=0.9",
        "vivid" to "eq=saturation=1.6:contrast=1.2",
        "noir" to "hue=s=0,eq=contrast=1.5:gamma=0.8,vignette=angle=PI/3",
        "bloom" to "eq=brightness=0.05:contrast=1.1,boxblur=luma_radius=5:luma_power=1,tblend=all_mode=screen",
        "tealorange" to "colorbalance=rs=0.12:gs=-0.05:bs=0.05:rm=0.1:bm=0.08,eq=saturation=1.3:contrast=1.15",
        "teal_orange" to "colorbalance=rs=0.12:gs=-0.05:bs=0.05:rm=0.1:bm=0.08,eq=saturation=1.3:contrast=1.15",
        "pastel" to "eq=saturation=0.7:brightness=0.08:contrast=0.95,colorbalance=rs=0.03:gs=0.02:bs=0.05",
        "fade" to "eq=saturation=0.6:contrast=0.9:brightness=0.05,colorbalance=rs=0.04:gs=0.02:bs=0.06",
        "cyberpunk" to "colorbalance=rs=0.2:bs=0.25:rm=0.1:bm=0.15,eq=saturation=1.8:contrast=1.3,hue=h=-20",
        "sunset" to "colorbalance=rs=0.15:rm=0.1:gs=-0.03,eq=saturation=1.4:contrast=1.1:gamma=1.05",
        "arctic" to "eq=saturation=0.9:contrast=1.1,colorbalance=bs=0.12:bm=0.08",
        "forest" to "eq=saturation=1.2:contrast=1.1,colorbalance=gs=0.1:gm=0.06:bs=-0.03",
        "rose" to "colorbalance=rs=0.1:rm=0.08:gs=-0.02:bs=0.04,eq=saturation=1.3:brightness=0.03",
        "golden" to "colorbalance=rs=0.12:rm=0.1:gs=0.03,eq=saturation=1.35:contrast=1.1:gamma=1.05,vignette=angle=PI/4",
        "mist" to "eq=contrast=0.9:saturation=0.8:brightness=0.1,boxblur=luma_radius=3:luma_power=1,tblend=all_mode=screen:all_opacity=0.3",
        "cinematic" to "eq=saturation=0.85:contrast=1.2:gamma=0.95,colorbalance=rs=0.04:bs=0.06",
        "teal" to "colorbalance=bs=0.15:bm=0.1:gs=0.03,eq=saturation=1.1:contrast=1.1",
        "orange" to "colorbalance=rs=0.15:rm=0.12,eq=saturation=1.2:contrast=1.1:gamma=1.05",
        "lomo" to "vignette=angle=PI/3,eq=saturation=1.5:contrast=1.3:gamma=0.9",
        "polaroid" to "eq=saturation=0.7:contrast=0.95:brightness=0.08,colorbalance=rs=0.05:bs=0.03,vignette=angle=PI/4",
        "holga" to "vignette=angle=PI/2,eq=saturation=1.3:contrast=1.1,noise=alls=10:allf=t",
        "diana" to "eq=saturation=1.4:contrast=0.9,vignette=angle=PI/2",
        "film" to "eq=saturation=0.9:contrast=1.05,noise=alls=8:allf=t",
        "super8" to "eq=saturation=1.2:brightness=0.05,noise=alls=15:allf=t,vignette=angle=PI/3",
        "vhs_tape" to "eq=saturation=1.1:contrast=0.95,noise=alls=12:allf=t",
        "kodak" to "eq=saturation=1.1:contrast=1.05:gamma=1.05,colorbalance=rs=0.05:gs=0.02",
        "fuji" to "eq=saturation=1.15:contrast=1.1,colorbalance=bs=0.04:gs=0.03",
        "agfa" to "eq=saturation=1.2:contrast=1.1,colorbalance=rs=0.06:bs=0.03",
        "ilford" to "hue=s=0,eq=contrast=1.2:gamma=1.05",
        "portra" to "eq=saturation=0.95:contrast=1.05:gamma=1.02,colorbalance=rs=0.04:gs=0.02:bs=0.02",
        "velvia" to "eq=saturation=1.5:contrast=1.2",
        "provia" to "eq=saturation=1.1:contrast=1.05",
        "astia" to "eq=saturation=1.0:contrast=1.0:gamma=1.05,colorbalance=rs=0.03:bs=0.03",
        "high_contrast" to "eq=contrast=1.5:saturation=1.1",
        "low_contrast" to "eq=contrast=0.85:saturation=0.95",
        "high_saturation" to "eq=saturation=2.0:contrast=1.1",
        "low_saturation" to "eq=saturation=0.5:contrast=1.0",
        "bright" to "eq=brightness=0.1:contrast=1.05:saturation=1.1",
        "dark" to "eq=brightness=-0.08:contrast=1.15:gamma=0.95",
        "soft" to "eq=contrast=0.9:saturation=0.9:brightness=0.05,boxblur=luma_radius=2:luma_power=1",
        "sharp" to "eq=contrast=1.3:saturation=1.2,unsharp=5:5:1:5:5:0",
        "dreamy" to "eq=saturation=1.1:brightness=0.08:contrast=0.95,boxblur=luma_radius=4:luma_power=1,tblend=all_mode=screen:all_opacity=0.3",
        "glow" to "eq=brightness=0.1:contrast=1.1,boxblur=luma_radius=6:luma_power=1,tblend=all_mode=screen:all_opacity=0.4",
        "haze" to "eq=contrast=0.85:saturation=0.8:brightness=0.12,boxblur=luma_radius=3:luma_power=1",
        "matte" to "eq=saturation=0.85:contrast=0.9:brightness=0.05",
        "litho" to "hue=s=0,eq=contrast=1.6:gamma=0.8",
        "sepia_warm" to "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,eq=saturation=1.1",
        "sepia_cool" to "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,eq=saturation=0.9",
        "red_boost" to "colorbalance=rs=0.2:rm=0.15,eq=saturation=1.2:contrast=1.1",
        "blue_boost" to "colorbalance=bs=0.2:bm=0.15,eq=saturation=1.2:contrast=1.1",
        "green_boost" to "colorbalance=gs=0.2:gm=0.15,eq=saturation=1.2:contrast=1.1",
        "purple_haze" to "colorbalance=rs=0.1:bs=0.15,eq=saturation=1.3:contrast=1.1,hue=h=15",
        "pink_dream" to "colorbalance=rs=0.12:bs=0.08,eq=saturation=1.3:brightness=0.05",
        "amber" to "colorbalance=rs=0.15:rm=0.1:gs=0.03,eq=saturation=1.25:gamma=1.05",
        "emerald" to "colorbalance=gs=0.15:gm=0.1:bs=0.03,eq=saturation=1.25",
        "sapphire" to "colorbalance=bs=0.15:bm=0.1,eq=saturation=1.2:contrast=1.05",
        "ruby" to "colorbalance=rs=0.18:rm=0.12,eq=saturation=1.3:contrast=1.1",
        "bronze" to "colorbalance=rs=0.1:rm=0.08:gs=0.05,eq=saturation=1.1:contrast=1.1:gamma=1.02",
        "platinum" to "eq=saturation=0.3:contrast=1.15:brightness=0.05",
        "neon_city" to "colorbalance=rs=0.15:bs=0.2:rm=0.1:bm=0.12,eq=saturation=1.8:contrast=1.3",
        "retro_wave" to "colorbalance=rs=0.18:bs=0.2:rm=0.1,eq=saturation=1.6:contrast=1.2,hue=h=-10",
        "synthwave" to "colorbalance=rs=0.15:bs=0.22,eq=saturation=1.7:contrast=1.25,hue=h=-15",
        "analog" to "eq=saturation=0.95:contrast=1.05,noise=alls=6:allf=t",
        "tokyo" to "colorbalance=rs=0.12:bs=0.1:rm=0.08,eq=saturation=1.4:contrast=1.15",
        "nyc" to "eq=saturation=0.9:contrast=1.3:gamma=0.95,colorbalance=bs=0.05",
        "paris" to "eq=saturation=1.05:contrast=1.1:gamma=1.02,colorbalance=rs=0.04:bs=0.03",
        "miami" to "colorbalance=rs=0.08:bs=0.12:gs=0.03,eq=saturation=1.5:contrast=1.1",
        "desert" to "colorbalance=rs=0.15:rm=0.1:gs=0.04,eq=saturation=1.2:contrast=1.1:gamma=1.05",
        "ocean" to "colorbalance=bs=0.15:bm=0.1:gs=0.05,eq=saturation=1.2:contrast=1.05",
        "autumn" to "colorbalance=rs=0.15:rm=0.12:gs=0.05,eq=saturation=1.3:contrast=1.1",
        "winter" to "eq=saturation=0.85:contrast=1.1,colorbalance=bs=0.1:bm=0.05",
        "spring" to "colorbalance=gs=0.08:bs=0.05:rs=0.03,eq=saturation=1.2:brightness=0.05",
        "summer" to "eq=saturation=1.3:contrast=1.1:brightness=0.05,colorbalance=rs=0.05:bs=0.03",
        "vibrant" to "eq=saturation=1.8:contrast=1.15",
        "moody" to "eq=saturation=0.7:contrast=1.4:brightness=-0.05,vignette=angle=PI/3",
        "ethereal" to "eq=saturation=1.1:brightness=0.12:contrast=0.9,boxblur=luma_radius=2:luma_power=1",
        "gritty" to "eq=saturation=0.8:contrast=1.5:brightness=-0.03,noise=alls=15:allf=t",
        "futuristic" to "hue=h=180,eq=saturation=1.6:contrast=1.2",
        "romantic" to "eq=saturation=1.1:brightness=0.06:contrast=0.95,colorbalance=rs=0.06:bs=0.02",
        "horror" to "eq=saturation=0.6:brightness=-0.1:contrast=1.4,colorbalance=gs=-0.05:bs=-0.03",
        "dream" to "eq=saturation=1.2:brightness=0.1:contrast=0.9,boxblur=luma_radius=3:luma_power=1",
        "noir_classic" to "hue=s=0,eq=contrast=1.4:gamma=0.85,vignette=angle=PI/2",
        "retro_film" to "eq=saturation=1.05:contrast=1.08:gamma=1.03,noise=alls=10:allf=t,colorbalance=rs=0.03",
        "candy" to "colorbalance=rs=0.08:bs=0.1:gs=0.02,eq=saturation=2.0:brightness=0.04",
        "noir_modern" to "hue=s=0,eq=contrast=1.6:gamma=0.9,colorbalance=bs=0.04",
        // ── User-requested 72 filters (new chains) ──
        "blur_light" to "boxblur=2:1",
        "blur_medium" to "boxblur=5:1",
        "blur_heavy" to "boxblur=10:2",
        "gaussian_blur" to "gblur=sigma=5",
        "sharpen_strong" to "unsharp=7:7:1.5:7:7:0.0",
        "brightness_10" to "eq=brightness=0.1",
        "brightness_20" to "eq=brightness=0.2",
        "brightness_30" to "eq=brightness=0.3",
        "brightness_neg10" to "eq=brightness=-0.1",
        "brightness_neg20" to "eq=brightness=-0.2",
        "contrast_20" to "eq=contrast=1.2",
        "contrast_40" to "eq=contrast=1.4",
        "contrast_neg20" to "eq=contrast=0.8",
        "saturation_0" to "eq=saturation=0",
        "saturation_50" to "eq=saturation=0.5",
        "saturation_150" to "eq=saturation=1.5",
        "saturation_200" to "eq=saturation=2.0",
        "vignette" to "vignette=PI/4",
        "vignette_strong" to "vignette=PI/2",
        "hflip" to "hflip",
        "vflip" to "vflip",
        "mirror_lr" to "hflip",
        "mirror_tb" to "vflip",
        "rotate_90" to "transpose=1",
        "rotate_180" to "transpose=2,transpose=2",
        "rotate_270" to "transpose=2",
        "green_tint" to "colorbalance=rs=-0.1:gs=0.3:bs=-0.1",
        "curves_drama" to "curves=0/0,0.1/0.05,0.5/0.6,0.9/0.95,1/1",
        "curves_retro" to "curves=0/0.1,0.3/0.4,0.7/0.7,1/0.9",
        "curves_highlight" to "curves=0/0,0.3/0.2,0.6/0.5,0.8/0.8,1/1",
        "increase_red" to "colorbalance=rs=0.4",
        "increase_green" to "colorbalance=gs=0.4",
        "increase_blue" to "colorbalance=bs=0.4",
        "decrease_red" to "colorbalance=rs=-0.3",
        "decrease_green" to "colorbalance=gs=-0.3",
        "decrease_blue" to "colorbalance=bs=-0.3",
        "solarize" to "eq=gamma=0.5:saturation=1.2",
        "solarize_strong" to "eq=gamma=0.3:saturation=1.5:brightness=0.1",
        "posterize_8" to "posterize=8",
        "posterize_4" to "posterize=4",
        "edge_detect" to "edgedetect",
        "emboss_filter" to "emboss",
        "film_grain" to "noise=alls=20",
        "film_grain_heavy" to "noise=alls=50",
        "pixelate" to "pixelize=10:10",
        "pixelate_medium" to "pixelize=15:15",
        "color_swap" to "colorchannelmixer=0:0:1:0:0:1:0:0:1:0:0:0",
        "sepia_vignette" to "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,vignette=PI/4",
        "warm_vintage_combo" to "colorbalance=rs=0.25:gs=0.05:bs=-0.15,eq=saturation=0.9:contrast=1.1,vignette=PI/5",
        "cold_blue_combo" to "colorbalance=rs=-0.2:gs=0.0:bs=0.3,eq=saturation=1.1:brightness=0.05",
        "vivid_cinema" to "eq=contrast=1.3:saturation=1.4:brightness=0.05,unsharp=3:3:0.8:3:3:0.0",
        "soft_dreamy" to "gblur=sigma=2,eq=brightness=0.1:saturation=1.1:contrast=0.9",
        "grayscale_contrast" to "hue=s=0,eq=contrast=1.3:brightness=-0.05",
        "blue_monochrome" to "hue=s=0,colorbalance=rs=-1:gs=-0.5:bs=1,eq=brightness=0.2",
        "red_monochrome" to "hue=s=0,colorbalance=rs=1:gs=-0.5:bs=-1,eq=brightness=0.2",
        "green_monochrome" to "hue=s=0,colorbalance=rs=-0.5:gs=1:bs=-0.5,eq=brightness=0.2",
        "purple_tone" to "colorbalance=rs=0.2:gs=-0.1:bs=0.3",
        "yellow_tone" to "colorbalance=rs=0.3:gs=0.2:bs=-0.2",
        "cyan_tone" to "colorbalance=rs=-0.2:gs=0.2:bs=0.3",
        "magenta_tone" to "colorbalance=rs=0.3:gs=-0.2:bs=0.2",
        // ── v7.3 — EXTENDED PROFESSIONAL FILTER CHAINS ──
        "teal_orange" to "colorbalance=rs=0.1:bs=0.15:rm=0.12:bm=0.1,eq=contrast=1.15:saturation=1.2",
        "matrix" to "colorbalance=gs=0.5:bs=0.0,eq=saturation=0.8:contrast=1.2,hue=h=110",
        "blade_runner" to "colorbalance=rs=0.05:bs=0.3:rm=0.1:bm=0.2,eq=saturation=1.5:contrast=1.3:brightness=-0.1",
        "tron" to "colorbalance=bs=0.4:gs=0.1,eq=saturation=2.0:contrast=1.4,hue=h=180",
        "vaporwave2" to "colorbalance=rs=0.3:bs=0.4:gs=-0.1,eq=saturation=1.8:contrast=1.2,hue=h=-30",
        "outrun" to "colorbalance=rs=0.4:bs=0.3:gs=-0.1,eq=saturation=1.6:contrast=1.3,hue=h=-40",
        "laser" to "colorbalance=rs=0.0:gs=0.5:bs=0.5,eq=saturation=2.5:contrast=1.5",
        "cyberpunk_neon" to "colorbalance=rs=0.25:bs=0.3,eq=saturation=2.2:contrast=1.4,hue=h=-20",
        "hollywood" to "colorbalance=rs=0.05:rm=0.1:bm=0.08,eq=contrast=1.2:saturation=1.2:gamma=1.05",
        "oscar" to "colorbalance=rs=0.08:gs=0.04:bs=0.1,eq=contrast=1.3:saturation=1.3:gamma=1.02",
        "thriller" to "colorbalance=bs=0.2:gs=0.1,eq=contrast=1.4:saturation=0.9:gamma=0.9",
        "horror" to "eq=contrast=1.5:saturation=0.7:gamma=0.7,colorbalance=gs=-0.2",
        "romance" to "colorbalance=rs=0.1:bs=0.05,eq=saturation=1.3:contrast=1.1:brightness=0.05",
        "action" to "eq=contrast=1.5:saturation=1.5:gamma=0.95,unsharp=3:3:1.0",
        "documentary" to "eq=contrast=1.1:saturation=0.85:gamma=1.0,colorbalance=gs=0.05",
        "news" to "eq=contrast=1.3:saturation=1.0:brightness=0.05,colorbalance=bs=0.05",
        "sport" to "eq=contrast=1.4:saturation=1.5:gamma=0.95,unsharp=5:5:0.8",
        "fashion" to "eq=saturation=1.3:contrast=1.2:brightness=0.08,unsharp=3:3:0.5",
        "wedding_warm" to "colorbalance=rs=0.1:gs=0.05,eq=saturation=1.2:contrast=1.05:brightness=0.08",
        "birthday" to "colorbalance=rs=0.1:gs=0.05:bs=0.1,eq=saturation=1.4:brightness=0.1",
        "baby" to "eq=saturation=0.85:contrast=0.95:brightness=0.12,colorbalance=rs=0.05:bs=0.03",
        "kids" to "colorbalance=rs=0.08:gs=0.05:bs=0.08,eq=saturation=1.3:brightness=0.1",
        "nature_green" to "colorbalance=gs=0.2,eq=saturation=1.3:contrast=1.1",
        "forest" to "colorbalance=gs=0.25:bs=0.05,eq=saturation=1.2:brightness=-0.05",
        "mountain" to "eq=saturation=1.1:contrast=1.2:gamma=1.0,colorbalance=bs=0.1",
        "beach" to "colorbalance=rs=0.05:gs=0.05:bs=0.15,eq=saturation=1.3:brightness=0.1",
        "tropical" to "colorbalance=gs=0.1:bs=0.05,eq=saturation=1.4:contrast=1.1",
        "city_day" to "eq=contrast=1.1:saturation=1.1:brightness=0.05",
        "city_night" to "colorbalance=bs=0.2,eq=contrast=1.2:brightness=-0.1",
        "studio" to "eq=contrast=1.1:saturation=1.0:brightness=0.05,unsharp=3:3:0.4",
        "moonlight" to "colorbalance=bs=0.2,eq=brightness=-0.15:saturation=0.8:contrast=1.1",
        "starlight" to "colorbalance=bs=0.15,eq=brightness=-0.1:saturation=1.2:contrast=1.2",
        "rainy_window" to "colorbalance=bs=0.1:gs=0.05,eq=saturation=0.85:contrast=0.9:brightness=-0.05",
        "foggy_morning" to "colorbalance=gs=0.1,eq=contrast=0.85:saturation=0.8:brightness=0.12",
        "snowy_day" to "colorbalance=bs=0.1:gs=0.05,eq=brightness=0.1:contrast=1.05:saturation=0.9",
        "autumn_leaves" to "colorbalance=rs=0.3:gs=0.1:bs=-0.15,eq=saturation=1.3",
        "cherry_blossom" to "colorbalance=rs=0.2:gs=-0.05:bs=0.1,eq=saturation=1.4:brightness=0.08",
        "lavender" to "colorbalance=bs=0.15:rs=0.1,eq=saturation=1.2:brightness=0.08",
        "rose_gold" to "colorbalance=rs=0.2:gs=0.1:bs=0.05,eq=saturation=1.2:brightness=0.1",
        "teal_grade" to "colorbalance=bs=0.2:gs=0.05,eq=contrast=1.1:saturation=1.2",
        "orange_grade" to "colorbalance=rs=0.2:rm=0.1,eq=contrast=1.1:saturation=1.2",
        "orange_teal" to "colorbalance=rs=0.15:bs=0.15:rm=0.1:bm=0.1,eq=contrast=1.15:saturation=1.3",
        "bleach_bypass" to "eq=contrast=1.5:saturation=0.6:gamma=0.9",
        "day_for_night" to "colorbalance=bs=0.3:gs=-0.1,eq=brightness=-0.2:saturation=0.8:contrast=1.2",
        "cross_process" to "colorbalance=rs=0.2:bs=0.2:gs=-0.1,eq=contrast=1.2:saturation=1.3",
        "lomo_fisheye" to "lenscorrection=k1=-0.3:k2=0.1,eq=contrast=1.4:saturation=1.3,vignette=PI/3",
        "instagram_1977" to "colorbalance=rs=0.15:gs=0.05,eq=saturation=1.2:contrast=1.1:brightness=0.05",
        "instagram_brannan" to "colorbalance=rs=0.1:gs=0.05:bs=0.1,eq=contrast=1.2:saturation=1.1",
        "instagram_earlybird" to "colorbalance=rs=0.15:gs=0.1,eq=contrast=1.1:saturation=1.2:brightness=0.03",
        "instagram_hefe" to "colorbalance=rs=0.1:gs=0.05:bs=0.05,eq=saturation=1.4:contrast=1.15",
        "instagram_lofi" to "colorbalance=rs=0.05:gs=0.05,eq=saturation=1.2:contrast=1.2",
        "instagram_ludwig" to "colorbalance=rs=0.1:bs=0.1,eq=contrast=1.1:saturation=1.1",
        "instagram_nashville" to "colorbalance=rs=0.2:bs=0.1,eq=saturation=1.3:contrast=1.05:brightness=0.08",
        "instagram_sutro" to "colorbalance=rs=0.1:bs=0.05,eq=contrast=1.2:brightness=-0.05:vignette=PI/4",
        "instagram_toaster" to "colorbalance=rs=0.2:gs=0.1,eq=saturation=1.3:brightness=0.05",
        "instagram_valencia" to "colorbalance=rs=0.15:gs=0.05:bs=0.05,eq=saturation=1.2:brightness=0.05",
        "instagram_walden" to "colorbalance=gs=0.1:bs=0.05,eq=saturation=1.3:brightness=0.05",
        "instagram_xproii" to "colorbalance=rs=0.2:gs=0.15:bs=-0.1,eq=contrast=1.3:saturation=1.4",
        "bw_classic" to "hue=s=0,eq=contrast=1.2",
        "bw_fade" to "hue=s=0,eq=contrast=0.85:brightness=0.1",
        "bw_strong" to "hue=s=0,eq=contrast=1.6:gamma=0.85",
        "sepia_light" to "colorchannelmixer=.3:.6:.15:0:.25:.5:.12:0:.2:.4:.1,eq=brightness=0.1",
        "sepia_dark" to "colorchannelmixer=.3:.6:.15:0:.25:.5:.12:0:.2:.4:.1,eq=brightness=-0.1:contrast=1.2",
        "cream" to "colorchannelmixer=.3:.6:.15:0:.25:.5:.12:0:.2:.4:.1,eq=saturation=0.7:brightness=0.12:contrast=0.95",
        "matte_film" to "eq=gamma=1.2:contrast=0.9:saturation=0.85,colorbalance=rs=0.05",
        "kodak_ektar" to "colorbalance=rs=0.1:gs=0.05:bs=0.05,eq=contrast=1.2:saturation=1.3",
        "kodak_portra" to "colorbalance=rs=0.08:gs=0.03:bs=0.05,eq=saturation=1.2:contrast=1.05",
        "fuji_superia" to "colorbalance=gs=0.1:bs=0.05,eq=contrast=1.15:saturation=1.25",
        "fuji_velvia" to "colorbalance=rs=0.15:gs=0.05:bs=0.1,eq=contrast=1.3:saturation=1.5",
        "ilford_hp5" to "hue=s=0,eq=contrast=1.3:gamma=0.95,noise=alls=8",
        "ilford_delta" to "hue=s=0,eq=contrast=1.4:gamma=0.9,noise=alls=5",
        "cinestill_800" to "colorbalance=rs=0.2:gs=0.05,eq=contrast=1.2:saturation=1.2:gamma=1.1",
        "bw_silver" to "hue=s=0,eq=contrast=1.25:gamma=1.0",
        "bw_ir" to "colorbalance=rs=0.5:gs=0.5:bs=-0.3,eq=contrast=1.4:brightness=-0.05",
        "golden_hour" to "colorbalance=rs=0.3:gs=0.15:bs=-0.1,eq=saturation=1.3:brightness=0.08:gamma=1.05",
        "blue_hour" to "colorbalance=bs=0.25:gs=0.05,eq=contrast=1.15:brightness=-0.05",
        "magic_hour" to "colorbalance=rs=0.25:gs=0.1:bs=0.1,eq=saturation=1.4:brightness=0.05",
        "pastel_sunset" to "colorbalance=rs=0.2:bs=0.15,eq=saturation=0.9:brightness=0.1:contrast=0.95",
        "dream_pop" to "gblur=sigma=1,eq=saturation=1.3:brightness=0.1:contrast=0.95",
        "lofi_chill" to "eq=contrast=0.9:saturation=0.85:gamma=1.1,colorbalance=rs=0.05",
        "studio_neon" to "colorbalance=bs=0.2:gs=0.1,eq=saturation=1.5:contrast=1.2",
        "k_pop" to "colorbalance=rs=0.15:bs=0.1,eq=saturation=1.6:contrast=1.2:brightness=0.05",
        "insta_airy" to "eq=brightness=0.12:contrast=0.9:saturation=1.1",
        "insta_moody" to "colorbalance=bs=0.1:gs=-0.05,eq=contrast=1.2:saturation=0.9:brightness=-0.05",
        "insta_clean" to "eq=saturation=1.05:contrast=1.05:brightness=0.05",
        "insta_fade_warm" to "colorbalance=rs=0.1:gs=0.05,eq=saturation=0.85:contrast=0.95:brightness=0.08",
        "insta_fade_cool" to "colorbalance=bs=0.1:gs=0.05,eq=saturation=0.85:contrast=0.95:brightness=0.08"
    )
}
