package com.powercut.editor.ui.editor

import androidx.compose.runtime.Composable
import com.powercut.editor.data.VideoProject

/**
 * EditorScreen — DEPRECATED stub.
 * The app uses NextGenEditorScreen exclusively.
 * This file exists only for binary compatibility.
 */
@Composable
fun EditorScreen(
    project: VideoProject,
    language: String,
    onBack: () -> Unit,
    onUpdateTrim: (Long, Long) -> Unit,
    onUpdateResolution: (String) -> Unit,
    onUpdateFilter: (String) -> Unit,
    onToggleMute: () -> Unit,
    onExport: () -> Unit,
    onDurationRetrieved: (Long) -> Unit,
    onUpdateSpeed: (Float) -> Unit,
    onUpdateAspectPreset: (String) -> Unit,
    onUpdateTransition: (String) -> Unit,
    onUpdateBackgroundMusic: (String?) -> Unit,
    onUpdateMusicVolume: (Float) -> Unit,
    onUpdateVideoVolume: (Float) -> Unit,
    onUpdateAutoCaptions: (String) -> Unit,
    onToggleSilenceRemover: () -> Unit,
    onUpdateRotation: () -> Unit,
    onToggleFlipHorizontal: () -> Unit,
    onToggleFlipVertical: () -> Unit,
    onUpdateCropPreset: (String) -> Unit,
    onUpdateSpeedCurve: (String) -> Unit,
    onUpdateTextOverlay: (String?) -> Unit,
    onUpdateTextAnimation: (String) -> Unit,
    onUpdateStickerType: (String) -> Unit,
    onUpdateTemplate: (String) -> Unit,
    onUpdateVisualizerStyle: (String) -> Unit,
    onToggleBeatSync: () -> Unit,
    onUpdate3DShapeMask: (String) -> Unit,
    onAddClip: (android.net.Uri) -> Unit,
    onSaveDraft: () -> Unit,
    onToggleGreenScreen: () -> Unit = {},
    onUpdateGreenScreenColor: (String) -> Unit = {},
    onUpdateGreenScreenThreshold: (Float) -> Unit = {},
    onSelectAutoBackground: (Int) -> Unit = {},
    onPickCustomBackground: () -> Unit = {},
    onUpdateEraserMode: (String) -> Unit = {},
    onUpdateEraserBrushSize: (Float) -> Unit = {},
    onUpdateEraserTolerance: (Float) -> Unit = {},
    onToggleEraserSoftEdge: () -> Unit = {},
    onUndoEraser: () -> Unit = {},
    onResetEraser: () -> Unit = {},
    onUpdateImageEditorBrightness: (Float) -> Unit = {},
    onUpdateImageEditorContrast: (Float) -> Unit = {},
    onUpdateImageEditorSaturation: (Float) -> Unit = {},
    onUpdateImageEditorBlur: (Float) -> Unit = {},
    onUpdateImageEditorSharpen: (Float) -> Unit = {},
    onUpdateImageEditorTemperature: (Float) -> Unit = {},
    onUpdateImageEditorVignette: (Float) -> Unit = {},
    onUpdateImageEditorGrain: (Float) -> Unit = {},
    onUpdateImageEditorFade: (Float) -> Unit = {},
    onUpdateImageEditorHighlights: (Float) -> Unit = {},
    onUpdateImageEditorShadows: (Float) -> Unit = {},
    onUpdateImageEditorExposure: (Float) -> Unit = {},
    onResetImageEditor: () -> Unit = {},
    onToggleTextBold: () -> Unit = {},
    onToggleTextItalic: () -> Unit = {},
    onToggleTextShadow: () -> Unit = {},
    onToggleTextOutline: () -> Unit = {},
    onToggleTextGlow: () -> Unit = {},
    onToggleTextNeon: () -> Unit = {},
    onUpdateTextBgColor: (String) -> Unit = {},
    onUpdateTextBgOpacity: (Float) -> Unit = {},
    onUpdateTextFontSize: (Float) -> Unit = {},
    onUpdateTextColor: (String) -> Unit = {},
    onUpdateTextStyle: (String) -> Unit = {},
    onUpdateTextPositionX: (Float) -> Unit = {},
    onUpdateTextPositionY: (Float) -> Unit = {},
    onUpdateOrientationMode: (String) -> Unit = {},
    onToggleVerticalSafeZone: () -> Unit = {},
    onToggleHorizontalLetterbox: () -> Unit = {},
    onToggleAutoReframe: () -> Unit = {},
    onAiHub: () -> Unit = {},
    onSocialPresets: () -> Unit = {},
    onProTier: () -> Unit = {},
    onPremiumStudio: () -> Unit = {},
    onOpenEffects: () -> Unit = {},
    onOpenStickers: () -> Unit = {}
) {
    // Delegate to NextGenEditorScreen — the real editor used by the app.
    NextGenEditorScreen(
        project = project,
        language = language,
        onBack = onBack,
        onUpdateTrim = onUpdateTrim,
        onUpdateResolution = onUpdateResolution,
        onUpdateFilter = onUpdateFilter,
        onToggleMute = onToggleMute,
        onExport = onExport,
        onDurationRetrieved = onDurationRetrieved,
        onUpdateSpeed = onUpdateSpeed,
        onUpdateAspectPreset = onUpdateAspectPreset,
        onUpdateTransition = onUpdateTransition,
        onUpdateBackgroundMusic = onUpdateBackgroundMusic,
        onUpdateMusicVolume = onUpdateMusicVolume,
        onUpdateVideoVolume = onUpdateVideoVolume,
        onUpdateAutoCaptions = onUpdateAutoCaptions,
        onToggleSilenceRemover = onToggleSilenceRemover,
        onUpdateRotation = onUpdateRotation,
        onToggleFlipHorizontal = onToggleFlipHorizontal,
        onToggleFlipVertical = onToggleFlipVertical,
        onUpdateCropPreset = onUpdateCropPreset,
        onUpdateSpeedCurve = onUpdateSpeedCurve,
        onUpdateTextOverlay = onUpdateTextOverlay,
        onUpdateTextAnimation = onUpdateTextAnimation,
        onUpdateTextStyle = onUpdateTextStyle,
        onUpdateTextPositionX = onUpdateTextPositionX,
        onUpdateTextPositionY = onUpdateTextPositionY,
        onUpdateTextColor = onUpdateTextColor,
        onUpdateTextFontSize = onUpdateTextFontSize,
        onUpdateStickerType = onUpdateStickerType,
        onUpdateTemplate = onUpdateTemplate,
        onUpdateVisualizerStyle = onUpdateVisualizerStyle,
        onToggleBeatSync = onToggleBeatSync,
        onUpdate3DShapeMask = onUpdate3DShapeMask,
        onAddClip = onAddClip,
        onSaveDraft = onSaveDraft,
        onToggleGreenScreen = onToggleGreenScreen,
        onUpdateGreenScreenColor = onUpdateGreenScreenColor,
        onUpdateGreenScreenThreshold = onUpdateGreenScreenThreshold,
        onSelectAutoBackground = onSelectAutoBackground,
        onPickCustomBackground = onPickCustomBackground,
        onUpdateEraserMode = onUpdateEraserMode,
        onUpdateEraserBrushSize = onUpdateEraserBrushSize,
        onUpdateEraserTolerance = onUpdateEraserTolerance,
        onToggleEraserSoftEdge = onToggleEraserSoftEdge,
        onUndoEraser = onUndoEraser,
        onResetEraser = onResetEraser,
        onUpdateImageEditorBrightness = onUpdateImageEditorBrightness,
        onUpdateImageEditorContrast = onUpdateImageEditorContrast,
        onUpdateImageEditorSaturation = onUpdateImageEditorSaturation,
        onUpdateImageEditorBlur = onUpdateImageEditorBlur,
        onUpdateImageEditorSharpen = onUpdateImageEditorSharpen,
        onUpdateImageEditorTemperature = onUpdateImageEditorTemperature,
        onUpdateImageEditorVignette = onUpdateImageEditorVignette,
        onUpdateImageEditorGrain = onUpdateImageEditorGrain,
        onUpdateImageEditorFade = onUpdateImageEditorFade,
        onUpdateImageEditorHighlights = onUpdateImageEditorHighlights,
        onUpdateImageEditorShadows = onUpdateImageEditorShadows,
        onUpdateImageEditorExposure = onUpdateImageEditorExposure,
        onResetImageEditor = onResetImageEditor,
        onUpdateOrientationMode = onUpdateOrientationMode,
        onToggleVerticalSafeZone = onToggleVerticalSafeZone,
        onToggleHorizontalLetterbox = onToggleHorizontalLetterbox,
        onToggleAutoReframe = onToggleAutoReframe,
        onAiHub = onAiHub,
        onSocialPresets = onSocialPresets,
        onProTier = onProTier,
        onPremiumStudio = onPremiumStudio,
        onOpenEffects = onOpenEffects,
        onOpenStickers = onOpenStickers
    )
}
