// shader-sources.js — GLSL sources as strings. Kept in one module so preview
// (main thread) and export (worker) load the EXACT same shader text.
export const SCREEN_VERT = `attribute vec4 a_position; attribute vec2 a_texCoord; varying vec2 v_texCoord; void main(){ gl_Position = a_position; v_texCoord = a_texCoord; }`;

export const FILTER_FRAG = `precision highp float; varying vec2 v_texCoord; uniform sampler2D u_src; uniform mat4 u_colorMatrix; void main(){ vec4 c = texture2D(u_src, v_texCoord); gl_FragColor = u_colorMatrix * c; }`;

export const CHROMA_KEY_FRAG = `precision highp float; varying vec2 v_texCoord; uniform sampler2D u_src; uniform sampler2D u_bg; uniform vec3 u_keyColor; uniform float u_tolerance; uniform float u_softness; uniform float u_spill; uniform float u_hasBg; uniform vec3 u_bgColor; uniform int u_blendMode; float colorDist(vec3 a, vec3 b){ vec3 d=a-b; return sqrt(dot(d,d)); } vec3 suppressSpill(vec3 c, vec3 key){ float k=max(key.r,max(key.g,key.b)); if(k<0.001) return c; float spill=clamp(u_spill,0.0,1.0); float denom=(1.0-key.r)+(1.0-key.g)+(1.0-key.b); float other=(c.r*(1.0-key.r)+c.g*(1.0-key.g)+c.b*(1.0-key.b))/max(denom,0.001); return mix(c,vec3(other),spill); } void main(){ vec4 src=texture2D(u_src,v_texCoord); vec3 rgb=src.rgb; vec3 lin=pow(rgb,vec3(2.2)); float d=colorDist(lin,u_keyColor); float t=u_tolerance; float edge=max(u_softness*0.5,0.001); float alpha=clamp((d-t)/edge,0.0,1.0); vec3 keyed=suppressSpill(rgb,u_keyColor); vec3 bg; if(u_hasBg>0.5){ bg=texture2D(u_bg,v_texCoord).rgb; } else { bg=u_bgColor; } vec3 out; if(u_blendMode==1){ out=mix(bg,keyed*bg,alpha); } else if(u_blendMode==2){ out=vec3(1.0)-(vec3(1.0)-mix(bg,keyed,alpha))*(vec3(1.0)-bg); } else if(u_blendMode==3){ out=mix(bg,keyed,alpha)+bg*(1.0-alpha); } else { out=keyed*alpha+bg*(1.0-alpha); } gl_FragColor=vec4(out,1.0); }`;

export const TRANSITION_FRAG = `precision highp float; varying vec2 v_texCoord; uniform sampler2D u_srcA; uniform sampler2D u_srcB; uniform float u_progress; uniform int u_type; uniform int u_ease; uniform vec2 u_dir; uniform float u_scale; float ease(float p,int e){ if(e==1) return p*p; if(e==2) return 1.0-(1.0-p)*(1.0-p); if(e==3) return p*p*(3.0-2.0*p); return p; } void main(){ float p=ease(clamp(u_progress,0.0,1.0),u_ease); vec4 a=texture2D(u_srcA,v_texCoord); vec4 b=texture2D(u_srcB,v_texCoord); vec4 out; if(u_type==0){ float noise=fract(sin(dot(v_texCoord,vec2(12.9898,78.233)))*43758.5453); float thresh=mix(0.5,1.0,p); out=mix(a,b,step(thresh,noise)); } else if(u_type==1){ out=mix(a,b,p); } else if(u_type==2){ vec2 off=u_dir*p; vec4 bShifted=texture2D(u_srcB,v_texCoord-off); out=mix(a,bShifted,p); } else if(u_type==3){ vec2 center=vec2(0.5); vec2 scaled=(v_texCoord-center)*(1.0+u_scale*p)+center; vec4 bZoom=texture2D(u_srcB,scaled); out=mix(a,bZoom,p); } else if(u_type==4){ float edge=v_texCoord.x+v_texCoord.y; float reveal=mix(-1.0,2.0,p); float mask=smoothstep(edge-0.05,edge+0.05,reveal); out=mix(b,a,mask); } else { out=mix(a,b,p); } gl_FragColor=out; }`;

export const VFX3D_FRAG = `precision highp float; varying vec2 v_texCoord; uniform sampler2D u_src; uniform float u_intensity; uniform float u_rotation; uniform float u_tilt; uniform float u_aberration; uniform float u_grain; uniform float u_scanlines; uniform float u_time; uniform vec2 u_resolution; mat2 rot2(float a){ float c=cos(a),s=sin(a); return mat2(c,-s,s,c); } void main(){ vec2 uv=v_texCoord-0.5; uv=rot2(u_rotation)*uv; uv+=0.5; vec4 r=texture2D(u_src,uv+vec2(u_aberration*0.01,0.0)); vec4 g=texture2D(u_src,uv); vec4 b=texture2D(u_src,uv-vec2(u_aberration*0.01,0.0)); vec4 col=vec4(r.r,g.g,b.b,1.0); float n=fract(sin(dot(uv,vec2(12.9898,78.233))+u_time)*43758.5453)-0.5; col.rgb+=n*u_grain; float line=sin(v_texCoord.y*u_resolution.y*2.0)*0.5+0.5; col.rgb*=1.0-u_scanlines*line*0.3; float tiltMask=1.0-u_tilt*abs(uv.x-0.5)*0.5; col.rgb*=tiltMask; gl_FragColor=col*u_intensity+texture2D(u_src,v_texCoord)*(1.0-u_intensity); }`;

export const BLEND_FRAG = `precision highp float; varying vec2 v_texCoord; uniform sampler2D u_frame; uniform sampler2D u_bg; uniform float u_bgAlpha; uniform int u_blendMode; void main(){ vec4 f=texture2D(u_frame,v_texCoord); vec4 bg=texture2D(u_bg,v_texCoord); vec4 out; if(u_blendMode==1){ out=vec4(f.rgb*bg.rgb,f.a); } else if(u_blendMode==2){ out=vec4(vec3(1.0)-(vec3(1.0)-f.rgb)*(vec3(1.0)-bg.rgb),f.a); } else if(u_blendMode==3){ out=vec4(f.rgb+bg.rgb,f.a); } else { float a=f.a+bg.a*(1.0-f.a); out=vec4((f.rgb*f.a+bg.rgb*bg.a*(1.0-f.a))/max(a,0.001),a); } out=mix(bg,out,u_bgAlpha); gl_FragColor=out; }`;